# Generated by Django 5.0.6 on 2024-06-01 22:24

from django.db import migrations


def create_initial_genres(apps, schema_editor):
    Genre = apps.get_model('movies', 'Genre')
    initial_genres = [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Horror",
        "Science Fiction",
        "Romance",
        "Suspense",
        "Thriller"
    ]
    for genre in initial_genres:
        Genre.objects.create(name=genre)

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_genres)
    ]
