# Generated by Django 5.0.6 on 2024-06-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_genre_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(help_text='Enter a duration in hours (e.g. 1.50)', max_length=3),
        ),
    ]
