# Generated by Django 5.0.6 on 2024-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='private',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
