# Generated by Django 5.0.6 on 2024-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_cast_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Animated', 'Animated'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Western', 'Western'), ('Other', 'Other')], max_length=100),
        ),
    ]
